#spring.application.name=mediLaboSolutionGateway
server:
  port: 8080
spring:
  application:
    name: mediLaboSolutionGateway
  cloud:
    gateway:
      routes:
        - id: patientInformation
          uri: http://localhost:8085
          predicates:
            - Path=/patient_info/**
        - id: patientPrescription
          uri: http://localhost:8086
          predicates:
            - Path=/prescription/**
        - id: analyse
          uri: http://localhost:8091
          predicates:
            - Path=/analyse/**
        - id: authentication
          uri: http://localhost:8082
          predicates:
            - Path=/login/**