#spring.application.name=mediLaboSolutionGateway
server:
  port: 8080
spring:
  application:
    name: mediLaboSolutionGateway
  cloud:
    gateway:
      routes:
        - id: patientInformation
          uri: http://patientinfocontainer:8085
          predicates:
            - Path=/patient_info/**
        - id: patientPrescription
          uri: http://patienthistorycontainer:8086
          predicates:
            - Path=/prescription/**
        - id: analyse
          uri: http://analysecontainer:8091
          predicates:
            - Path=/analyse/**